### ISSUE TITLE
rework checklist

### ISSUE THREAD

**Issue by btwonion** [SickMC/SickCore#12]
- [ ] vanish
- [ ] maintenance
- [ ] location command for buildserver
- [ ] Build tools command for buildserver
- [ ] lobby plugin
- [x] skull/mob drops for survival
- [x] add starting equip for survival
- [ ] combat/chest log for survival
- [x] sharepos command for survival 
- [ ] remake commands: find/send/server/list
- [x] discord log
- [x] discord leveling
- [x] remove botchat
- [ ] auto ranks
- [x] staff commands: clear/ announce channel on private dc
- [x] ticket system
- [ ] verify system

**Comment by btwonion** [comment]
ac2e57d74073be1711157bd9bc933159e12ae006

**Comment by btwonion** [comment]
another rework from paper to fabric:

- [ ] tablist
- [ ] sickPlayer handling (caching on join)
- [ ] custom events
- [ ] create MessageReceiver
